Unify all `<app_id>_control`
DUNE-DAQ/daqsystemtest pull request #162
Opened 2024-11-19 17:48 UTC by plasorak

This PR uses https://github.com/DUNE-DAQ/confmodel/pull/53 to make the application configuration simpler, by removing all the `<app_id>_control` services and unifying them in `daqapp_control` and `drunc_control`.

2024-11-19 22:35 UTC, alessandrothea requested changes
LGTM, just a comment about one of the names

2024-11-19 22:35 UTC, alessandrothea commented on config/daqsystemtest/ccm.data.xml
> +<obj class="Service" id="drunc_control">
maybe `rccontroller_control`?

2024-11-20 15:13 UTC, alessandrothea approved these changes

2024-11-20 19:52 UTC, eflumerf approved these changes

2024-11-20 19:58 UTC, merged